name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for index.html
        run: |
          if [ ! -s index.html ]; then
            echo "index.html is missing or empty"
            exit 1
          fi

      # Add your deployment steps below
      # Example: Deploy to GitHub Pages (if using)
      # - name: Deploy to GitHub Pages
      #   uses: peaceiris/actions-gh-pages@v4
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: .